apiVersion: v1
kind: Service
metadata:
  name: fronted-service
  labels:
    app: fronted
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: fronted
    tier: fronted
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fronted-deployment
  labels:
    app: fronted
spec:
  selector:
    matchLabels:
      app: fronted
      tier: fronted
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: fronted
        tier: fronted
    spec:
      containers:
      - name: fronted
        image: juancarlospina/nube.sanvalero:WEB1 # Reemplaza esto con tu imagen Docker del backend
        ports:
        - containerPort: 80
